In [6]:
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

#### *Đọc file txt* ####

In [4]:
with open('ma_so_thi_sinh_binh_thuan.txt', 'r') as file:
    ma_so_thi_sinh = file.read().splitlines()

#### *Tạo driver* ####

In [7]:
driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
driver.maximize_window()
driver.get('https://vtv.vn/tra-cuu-diem-thi-2023.htm')
time.sleep(2)

#### *Nhập dữ liệu và ấn vào nút tìm kiếm trên trang web https://vtv.vn/tra-cuu-diem-thi-2023.htm* ####

In [1]:
result_list = []
for ma_so in ma_so_thi_sinh:
    result_dict = {}
    # Tìm phần tử là ô tìm kiếm
    search_box = driver.find_element(By.ID, "keyworddiemthi")
    search_box.clear()
    search_box.send_keys(str(ma_so))

    # Tìm phần tử là nút search và thực hiện click
    search_button = driver.find_element(By.ID, "btnSearchDiemThi")
    search_button.click()
    time.sleep(0.5)

    # Tìm phần tử là bảng kết quả tìm kiếm
    search_box = driver.find_element(By.ID, "searchresult")
    text = search_box.text
    lst = text.split('\n')

    for item in lst:
        # Tách chuỗi theo dấu ':', lấy phần bên phải là giá trị
        parts = item.split(':')
        key = parts[0].strip()
        value = parts[1].strip()
        result_dict[key] = value
    # Thêm từ điển của thí sinh vào danh sách
    result_list.append(result_dict)

df = pd.DataFrame(result_list)
df.columns = ['SBD', 'Toan', 'Van', 'Ly', 'Hoa', 'Sinh', 'Su', 'Dia', 'GDCD', 'NgoaiNgu', 'MaNgoaiNgu']
print(df)

NameError: name 'ma_so_thi_sinh' is not defined

#### *Thêm cột tên ngoại ngữ* ####

In [ ]:
language = {
    'N1': 'Tiếng Anh',
    'N2': 'Tiếng Nga',
    'N3': 'Tiếng Pháp',
    'N4': 'Tiếng Trung',
    'N5': 'Tiếng Đức',
    'N6': 'Tiếng Nhật'
}
df['TenNgoaiNgu'] = df['MaNgoaiNgu'].replace(language)
print(df)

            SBD Toan   Van    Ly   Hoa  Sinh    Su   Dia  GDCD NgoaiNgu  \
0      47000001  7.4     8  7.25     7  8.25                        6.4
1      47000002  8.6     7                    8.75  7.75   8.5      6.6
2      47000003    7     7   8.5  7.25     8                        8.4
3      47000004  6.4  5.75   4.5  4.25     4                        5.2
4      47000005  4.2     3                     5.5   6.5
...         ...  ...   ...   ...   ...   ...   ...   ...   ...      ...
12835  47012896    6     7                    6.75     6   9.5      5.8
12836  47012897  5.6     7                    4.25   5.5  8.25      2.8
12837  47012898  2.6  6.25                     3.5  5.25   6.5      2.6
12838  47012899    2     6                       5     5   8.5      2.2
12839  47012900  4.4     7                       6     6  8.75      4.8

      MaNgoaiNgu TenNgoaiNgu
0             N1   Tiếng Anh
1             N1   Tiếng Anh
2             N1   Tiếng Anh
3             N1   Tiếng Anh
4           null        null
...          ...         ...
12835         N1   Tiếng Anh
12836         N1   Tiếng Anh
12837         N1   Tiếng Anh
12838         N1   Tiếng Anh
12839         N1   Tiếng Anh

[12840 rows x 12 columns]

#### *Thêm cột tên mã cụm thi* ####

In [ ]:
df['MaCumThi'] = 47.0
print(df)

            SBD Toan   Van    Ly   Hoa  Sinh    Su   Dia  GDCD NgoaiNgu  \
0      47000001  7.4     8  7.25     7  8.25                        6.4
1      47000002  8.6     7                    8.75  7.75   8.5      6.6
2      47000003    7     7   8.5  7.25     8                        8.4
3      47000004  6.4  5.75   4.5  4.25     4                        5.2
4      47000005  4.2     3                     5.5   6.5
...         ...  ...   ...   ...   ...   ...   ...   ...   ...      ...
12835  47012896    6     7                    6.75     6   9.5      5.8
12836  47012897  5.6     7                    4.25   5.5  8.25      2.8
12837  47012898  2.6  6.25                     3.5  5.25   6.5      2.6
12838  47012899    2     6                       5     5   8.5      2.2
12839  47012900  4.4     7                       6     6  8.75      4.8

      MaNgoaiNgu TenNgoaiNgu  MaCumThi
0             N1   Tiếng Anh      47.0
1             N1   Tiếng Anh      47.0
2             N1   Tiếng Anh      47.0
3             N1   Tiếng Anh      47.0
4           null        null      47.0
...          ...         ...       ...
12835         N1   Tiếng Anh      47.0
12836         N1   Tiếng Anh      47.0
12837         N1   Tiếng Anh      47.0
12838         N1   Tiếng Anh      47.0
12839         N1   Tiếng Anh      47.0

[12840 rows x 13 columns]

#### *Thêm cột tên cụm thi* ####

In [ ]:
df['TenCumThi'] = 'Sở GDĐT Bình Thuận'
print(df)

            SBD Toan   Van    Ly   Hoa  Sinh    Su   Dia  GDCD NgoaiNgu  \
0      47000001  7.4     8  7.25     7  8.25                        6.4
1      47000002  8.6     7                    8.75  7.75   8.5      6.6
2      47000003    7     7   8.5  7.25     8                        8.4
3      47000004  6.4  5.75   4.5  4.25     4                        5.2
4      47000005  4.2     3                     5.5   6.5
...         ...  ...   ...   ...   ...   ...   ...   ...   ...      ...
12835  47012896    6     7                    6.75     6   9.5      5.8
12836  47012897  5.6     7                    4.25   5.5  8.25      2.8
12837  47012898  2.6  6.25                     3.5  5.25   6.5      2.6
12838  47012899    2     6                       5     5   8.5      2.2
12839  47012900  4.4     7                       6     6  8.75      4.8

      MaNgoaiNgu TenNgoaiNgu  MaCumThi           TenCumThi
0             N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
1             N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
2             N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
3             N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
4           null        null      47.0  Sở GDĐT Bình Thuận
...          ...         ...       ...                 ...
12835         N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
12836         N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
12837         N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
12838         N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận
12839         N1   Tiếng Anh      47.0  Sở GDĐT Bình Thuận

[12840 rows x 14 columns]

In [ ]:
df

,SBD,Toan,Van,Ly,Hoa,Sinh,Su,Dia,GDCD,NgoaiNgu,MaNgoaiNgu,TenNgoaiNgu,MaCumThi,TenCumThi
0,47000001,7.4,8,7.25,7,8.25,,,,6.4,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
1,47000002,8.6,7,,,,8.75,7.75,8.5,6.6,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
2,47000003,7,7,8.5,7.25,8,,,,8.4,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
3,47000004,6.4,5.75,4.5,4.25,4,,,,5.2,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
4,47000005,4.2,3,,,,5.5,6.5,,,null,null,47.0,Sở GDĐT Bình Thuận
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12835,47012896,6,7,,,,6.75,6,9.5,5.8,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
12836,47012897,5.6,7,,,,4.25,5.5,8.25,2.8,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
12837,47012898,2.6,6.25,,,,3.5,5.25,6.5,2.6,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
12838,47012899,2,6,,,,5,5,8.5,2.2,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận
12839,47012900,4.4,7,,,,6,6,8.75,4.8,N1,Tiếng Anh,47.0,Sở GDĐT Bình Thuận

#### *Lưu thành file CSV* ####

In [ ]:
# Lưu dataframe thành tệp CSV
df.to_csv('data.csv', encoding='utf-16')

#### *Thống kê số lượng điểm thi của từng môn* ####

In [ ]:
subject_counts = df[['Toan', 'Ly', 'Hoa', 'Sinh', 'Van', 'Su', 'Dia', 'GDCD', 'NgoaiNgu']].apply(pd.to_numeric, errors='coerce').count()
subject_counts = subject_counts.reset_index()
subject_counts = subject_counts.transpose()
subject_counts.columns = subject_counts.iloc[0]
subject_counts = subject_counts[1:]
subject_counts = subject_counts.astype(int)

subject_counts.columns = ['SL_Toan', 'SL_Ly', 'SL_Hoa', 'SL_Sinh', 'SL_Van', 'SL_Su', 'SL_Dia', 'SL_GDCD', 'SL_NgoaiNgu']
subject_counts

,SL_Toan,SL_Ly,SL_Hoa,SL_Sinh,SL_Van,SL_Su,SL_Dia,SL_GDCD,SL_NgoaiNgu
0,12663,3904,3895,3860,12748,8878,8855,8283,12166